apiVersion: v1
kind: ConfigMap
metadata:
    name: frontend-config
    namespace: {{ .Values.namespace.name }}
    labels:
        app: frontend
data:
    default.conf: |
        server {
            listen {{ .Values.frontend.config.listenPort }};
            server_name _;

            root /usr/share/nginx/html;
            index index.html;

            location / {
                try_files {{ `$uri $uri/ /index.html` }};
            }

            location /api/ {
                proxy_pass http://{{ .Values.frontend.config.backendService }}:{{ .Values.frontend.config.backendPort }}/;
                proxy_http_version 1.1;
                proxy_set_header Host {{ `$host` }};
                proxy_set_header X-Forwarded-For {{ `$proxy_add_x_forwarded_for` }};
                proxy_set_header X-Forwarded-Proto {{ `$scheme` }};
            }
        }
