apiVersion: v1
kind: Service
metadata:
    name: backend
    namespace: {{ .Values.namespace.name }}
    labels:
        app: backend
spec:
    selector:
        app: backend
    ports:
      - name: http
        port: {{ .Values.backend.service.port }}
        targetPort: {{ .Values.backend.config.port }}
        protocol: TCP
    type: {{ .Values.backend.service.type }}
