- name: Initialize the control plane
  hosts: control_plane
  become: true
  
  vars:
    apiserver: '192.168.122.10'
    cidr: '10.0.0.0/16'
  
  tasks:
    
  - name: Check /etc/kubernetes/admin.conf
    ansible.builtin.stat:
      path: /etc/kubernetes/admin.conf
    register: k8s_conf_status
  
  - name: Kubeadm init
    ansible.builtin.command:
      argv:
        - kubeadm
        - init
        - --apiserver-advertise-address={{ apiserver }} # адрес на котором ip сервер принимает подключения
        - --pod-network-cidr={{ cidr }} 
    when: not k8s_conf_status.stat.exists

  - name: Create /root/.kube
    ansible.builtin.file:
      path: /root/.kube
      state: directory
      owner: root
      group: root
      mode: '0700'

  - name: COPY /etc/kubernetes/admin.conf > /root/.kube/admin.conf
    ansible.builtin.copy:
      src: /etc/kubernetes/admin.conf
      dest: /root/.kube/config
      remote_src: true # копирует с целевой системы, а не хостовой
      owner: root
      group: root
      mode: '0600'

  